services:
  mysql:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=data
volumes:
  postgres-data: